### ISSUE TITLE
SignUp and Login Forms

### ISSUE THREAD

**Issue by highb33kay** [zuri-training/Team_20-proj-my_cms#7]
Some of us has been assigned here, please we would be working with strict deadlines

**Comment by ejena-black** [comment]
Done, Please Review

**Comment by highb33kay** [comment]
Login Forms are ready for integration with core.

**Comment by highb33kay** [comment]
Login Forms are ready for integration with core. @MikeSoft007 @buike5

**Comment by MikeSoft007** [comment]
Copied @highb33kay
